### ISSUE TITLE
Some brains have neurons connected to themselves

### ISSUE THREAD

**Issue by djordje-jovic** [BackyardBrains/NeuroRobot#7]
### Some brains have neurons connected to themselves

List of brains with issue:
* Chopin
* Mocho
* Momo
* Opportunity
* Reservoir
* Vomba

In matrix: `connectome` for brains above, there are neurons which have some value more than zero for the same column number (e.g. row 3, column 3). which means it is connected to it self.

**Comment by gagegreg** [comment]
Moving to Flutter
